### ISSUE TITLE
How to build file

### ISSUE THREAD

**Issue by hieunmfake** [taoqi98/PP-Rec#4]
Great works!
I want to ask some questions about build some specific files:
In NewsContent.py, 
we have mergeimps.tsv:
![image](https://user-images.githubusercontent.com/86345035/161522725-775f7a85-daf3-458a-b7bd-41879f1b00ad.png)
and V21UrlDocs22_title_josn.tsv:
![image](https://user-images.githubusercontent.com/86345035/161522810-9da9de85-9246-4c47-bd66-c3865a4a4ad7.png)
I want to ask how to build that files, from MIND Dataset.
One more, can you show me one sample of each text file, so i can rebuild for myself.
Many thanks

**Comment by taoqi98** [comment]
Thank you for your attention to our work.

For implementing our method based on MIND, the "V21UrlDocs22_title_json.tsv'' needs to store all news in the training/val/test set. Each line stores the information of a single news article, where format is based on ``[News_ID] TAB [Category] TAB [Subcategory] TAB [Title] TAB [Url] TAB [Abstract] TAB [Body]. You can modify my codes to avoid the load of some unnecessary news data (e.g., Url, Abstract, and Body)

The "mergeimps.tsv'' file needs to store the #click and #impression of each news with time information for building popularity signals. Specifically, we first need to divide the time into several buckets in units of one hour. Thus, since the MIND dataset contains user data in 6 weeks, the time periods can be divided into 24*7*6 buckets. Then, we count the #impressions and #clicks of a news in each bucket and store the results in each line of ``mergeimps.tsv'', where the format is [News_ID] TAB [Bucket_ID] TAB #Cliks TAB #Impressions. In MIND, since we did not obtain the click information for test data, which can substantially affect the estimation of popularity signals. Thus, I advise that you can use the validation dataset of MIND for evaluation.
